#! /bin/sh

sxhkd &

xrdb -load .Xresources
~/.local/scripts/displayconf.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config remove_unplugged_monitors true


bspc rule -a Chromium-browser desktop=WEB state=monocle follow=on
bspc rule -a Emacs24 desktop=DEV state=tiled follow=on
bspc rule -a Pcmanfm desktop=SYS state=tiled follow=on
bspc rule -a Transmission-gtk desktop=SYS state=float follow=off

compton &
